// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZV8b8aRk2Q9Ka0J608VrkIKiIK3LuZu0',
    appId: '1:159145142391:web:95180a40938b7d1f9f3e72',
    messagingSenderId: '159145142391',
    projectId: 'blood-donation-5b9fe',
    authDomain: 'blood-donation-5b9fe.firebaseapp.com',
    storageBucket: 'blood-donation-5b9fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0aFem7nlomK_7C0je8QYnrXUIeVlRmiA',
    appId: '1:159145142391:android:a11a53cbcc36612e9f3e72',
    messagingSenderId: '159145142391',
    projectId: 'blood-donation-5b9fe',
    storageBucket: 'blood-donation-5b9fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVOoWrM6ON1GlQ6Pdn-j_DTaSXXkl21bY',
    appId: '1:159145142391:ios:5f084fb735a9725c9f3e72',
    messagingSenderId: '159145142391',
    projectId: 'blood-donation-5b9fe',
    storageBucket: 'blood-donation-5b9fe.appspot.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVOoWrM6ON1GlQ6Pdn-j_DTaSXXkl21bY',
    appId: '1:159145142391:ios:5b2d0d4e0b3669f59f3e72',
    messagingSenderId: '159145142391',
    projectId: 'blood-donation-5b9fe',
    storageBucket: 'blood-donation-5b9fe.appspot.com',
    iosBundleId: 'com.example.bloodDonation.RunnerTests',
  );
}
